site_name: Weissbourd Lab Wiki
theme:
  name: material
nav:
  - Home: index.md
  - Protocols: protocols.md
  - Inventory: inventory.md
  - Analysis Tools: analysis-tools.md
  - Jellyfish Maintenance: jellyfish-maintenance.md
  - Literature: literature.md

extra_css:
  - assets/custom.css
